# ------------------------------------------------------------------------------
# Project Euler - Problem 002 - Even Fibonacci numbers
# ------------------------------------------------------------------------------
# Problem Link: https://projecteuler.net/problem=002
# ------------------------------------------------------------------------------
# Author: Paul Frisby
# Email: mail@paulfrisby.com
# Github: https://github.com/paulfrisby/
# ------------------------------------------------------------------------------


# ------------------------------------------------------------------------------
# Problem Definition
# ------------------------------------------------------------------------------
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
# ------------------------------------------------------------------------------


# ------------------------------------------------------------------------------
# Main Code
# ------------------------------------------------------------------------------

# returns sum of all Fibonacci numbers up to a given limit
# takes optional factor argument to only sum Fibonnacci numbers which divide evenly in to this factor
def fibonacciSum(limit, factor=1):

    # initiailise with first 2 Fibonacci numbers
    fib1 = 1
    fib2 = 2
    
    total = 0
    while fib2 < limit:
        if fib1%factor == 0:
            total += fib1
        if fib2%factor == 0:
            total += fib2

        # generate next 2 fibonacci numbers
        fib1 += fib2
        fib2 += fib1

    # runs only is the last generated Fibonacci number is over the limit, but 2nd last is not
    # this is needed as the while loop works on 2 numbers per runthrough, but not always both of them will be over the limit
    if fib1 < limit:
        total += fib1
        
    return total

print (fibonacciSum(4000000, factor=2))
